//============================================================================
// top_level.v
// DE1-SoC Top-Level Module — CAN Sensor Fusion Platform
//
// Target:  Intel Cyclone V SoC (5CSEMA5F31C6), DE1-SoC board
// Clock:   CLOCK_50 = 50 MHz
//
// This module instantiates the complete CAN sensor fusion pipeline:
//   1. mcp2515_controller — drives MCP2515 CAN transceiver via SPI
//   2. can_sensor_axi_slave — Avalon-MM register file with timestamp,
//      FIR filtering, and accelerometer extraction
//   3. led_status — visual feedback on LEDs and 7-segment displays
//
// GPIO_0 Pin Mapping (directly to MCP2515 breakout):
//   GPIO_0[0] = SPI_SCK       (output)
//   GPIO_0[1] = SPI_MOSI      (output)
//   GPIO_0[2] = SPI_MISO      (input)
//   GPIO_0[3] = SPI_CS_N      (output)
//   GPIO_0[4] = MCP2515_INT_N (input, active low)
//
// KEY[0] = active-low reset (directly from push button)
// SW[9]  = enable/disable FIR filtering (active high = filtered)
//
// HPS Interface:
//   The HPS-to-FPGA lightweight bridge is generated by Qsys/Platform
//   Designer.  A placeholder comment marks where the hps_0 instance
//   would connect.  The Avalon-MM slave signals are wired to the
//   can_sensor_axi_slave module.
//============================================================================

module top_level (
    // ---- Clock ----
    input  wire        CLOCK_50,

    // ---- Keys (active low) ----
    input  wire [3:0]  KEY,

    // ---- Switches ----
    input  wire [9:0]  SW,

    // ---- LEDs ----
    output wire [9:0]  LEDR,

    // ---- Seven-Segment Displays (active low) ----
    output wire [6:0]  HEX0,
    output wire [6:0]  HEX1,
    output wire [6:0]  HEX2,
    output wire [6:0]  HEX3,
    output wire [6:0]  HEX4,
    output wire [6:0]  HEX5,

    // ---- GPIO Header 0 ----
    inout  wire [35:0] GPIO_0

    // ---- HPS interface ports (directly from Qsys) ----
    // In a real build, Qsys generates the HPS wrapper with these ports.
    // They are left commented out here; the Platform Designer system
    // (hps_0) is instantiated as a placeholder below.
    //
    // input  wire        hps_io_hps_io_emac1_inst_TX_CLK,
    // ... (full HPS I/O list omitted — auto-generated by Qsys)
);

    // ================================================================
    // Internal wires and resets
    // ================================================================
    wire clk   = CLOCK_50;
    wire rst_n = KEY[0];           // KEY[0] active-low, directly usable

    // ================================================================
    // GPIO pin assignments — directly drive/read GPIO_0
    // ================================================================
    wire spi_sclk;
    wire spi_mosi;
    wire spi_miso;
    wire spi_cs_n;
    wire mcp_int_n;

    // Directly assign SPI outputs to GPIO_0 pins
    assign GPIO_0[0] = spi_sclk;       // SPI clock to MCP2515
    assign GPIO_0[1] = spi_mosi;       // MOSI to MCP2515
    assign spi_miso  = GPIO_0[2];      // MISO from MCP2515 (input)
    assign GPIO_0[3] = spi_cs_n;       // Chip select to MCP2515
    assign mcp_int_n = GPIO_0[4];      // Interrupt from MCP2515 (input)

    // Unused GPIO_0 pins — set to high-impedance
    assign GPIO_0[35:5] = 31'bz;

    // ================================================================
    // CAN controller (MCP2515 via SPI)
    // ================================================================
    wire [10:0] can_id;
    wire [63:0] can_data;
    wire [3:0]  can_dlc;
    wire        can_valid;
    wire        can_error;

    mcp2515_controller u_mcp2515 (
        .clk       (clk),
        .rst_n     (rst_n),
        .int_n     (mcp_int_n),
        .spi_sclk  (spi_sclk),
        .spi_mosi  (spi_mosi),
        .spi_miso  (spi_miso),
        .spi_cs_n  (spi_cs_n),
        .can_id    (can_id),
        .can_data  (can_data),
        .can_dlc   (can_dlc),
        .can_valid (can_valid),
        .can_error (can_error)
    );

    // ================================================================
    // Avalon-MM Slave — register file, timestamp, FIR, accel parsing
    // ================================================================
    //
    // In a full Qsys build the Avalon-MM address, readdata, writedata,
    // read, write, chipselect signals come from the HPS lightweight
    // bridge master.  For standalone synthesis/simulation we provide
    // directly driven stub signals; in production these are replaced
    // by Qsys-generated interconnect wires.
    //
    wire [4:0]  avl_address;
    wire [31:0] avl_writedata;
    wire [31:0] avl_readdata;
    wire        avl_read;
    wire        avl_write;
    wire        avl_chipselect;

    wire signed [15:0] accel_raw_x;
    wire signed [15:0] accel_raw_y;
    wire signed [15:0] accel_raw_z;
    wire [31:0] frame_count;
    wire [31:0] error_count;
    wire [31:0] timestamp;

    can_sensor_axi_slave u_axi_slave (
        .clk            (clk),
        .rst_n          (rst_n),
        .address        (avl_address),
        .writedata      (avl_writedata),
        .readdata       (avl_readdata),
        .read           (avl_read),
        .write          (avl_write),
        .chipselect     (avl_chipselect),
        .can_id         (can_id),
        .can_data       (can_data),
        .can_dlc        (can_dlc),
        .can_valid      (can_valid),
        .can_error      (can_error),
        .accel_raw_x    (accel_raw_x),
        .accel_raw_y    (accel_raw_y),
        .accel_raw_z    (accel_raw_z),
        .frame_count_out(frame_count),
        .error_count_out(error_count),
        .timestamp_out  (timestamp)
    );

    // ================================================================
    // LED and 7-segment status display
    // ================================================================
    led_status u_led_status (
        .clk         (clk),
        .rst_n       (rst_n),
        .can_valid   (can_valid),
        .can_error   (can_error),
        .frame_count (frame_count),
        .accel_x     (accel_raw_x),
        .sw          (SW),
        .ledr        (LEDR),
        .hex0        (HEX0),
        .hex1        (HEX1),
        .hex2        (HEX2),
        .hex3        (HEX3),
        .hex4        (HEX4),
        .hex5        (HEX5)
    );

    // ================================================================
    // HPS System (Qsys / Platform Designer generated)
    //
    // In a full build, Platform Designer generates an HPS wrapper
    // module (typically named "soc_system") that contains:
    //   - hps_0: the HPS core (ARM Cortex-A9 dual core)
    //   - Lightweight HPS-to-FPGA bridge master
    //   - FPGA-to-HPS bridge (if used)
    //   - DDR3 controller, peripheral I/O muxing
    //
    // The lightweight bridge master's Avalon-MM signals connect to
    // our can_sensor_axi_slave.  Example instantiation:
    //
    //   soc_system u_soc_system (
    //       .clk_clk                       (CLOCK_50),
    //       .reset_reset_n                 (rst_n),
    //
    //       // Lightweight HPS-to-FPGA bridge
    //       .hps_0_h2f_lw_axi_master_awaddr  (...),
    //       // ... AXI signals auto-connected in Qsys ...
    //
    //       // Exported Avalon-MM conduit to our slave
    //       .can_sensor_slave_address      (avl_address),
    //       .can_sensor_slave_readdata     (avl_readdata),
    //       .can_sensor_slave_writedata    (avl_writedata),
    //       .can_sensor_slave_read         (avl_read),
    //       .can_sensor_slave_write        (avl_write),
    //       .can_sensor_slave_chipselect   (avl_chipselect),
    //
    //       // HPS I/O (directly to board pins)
    //       .hps_io_hps_io_emac1_inst_TX_CLK (HPS_ENET_GTX_CLK),
    //       // ... remaining HPS I/O pins ...
    //
    //       // HPS DDR3
    //       .memory_mem_a                  (HPS_DDR3_ADDR),
    //       // ... remaining DDR3 pins ...
    //   );
    //
    // For standalone synthesis without HPS, tie off the Avalon signals:
    // ================================================================
    assign avl_address    = 5'd0;
    assign avl_writedata  = 32'd0;
    assign avl_read       = 1'b0;
    assign avl_write      = 1'b0;
    assign avl_chipselect = 1'b0;

endmodule
